#!/bin/sh

# LAN IP
uci -q set network.lan.ipaddr='192.168.1.1'
uci -q set network.lan.netmask='255.255.255.0'

# DHCP
uci -q set dhcp.lan=dhcp
uci -q set dhcp.lan.interface='lan'
uci -q set dhcp.lan.start='100'
uci -q set dhcp.lan.limit='150'
uci -q set dhcp.lan.leasetime='12h'
uci -q set dhcp.lan.ignore='0'

# Chinese
uci -q set luci.main.lang='zh_cn'
uci -q set luci.languages.zh_cn='简体中文'
uci -q set luci.languages.en='English'

# Aurora theme
uci -q set luci.main.mediaurlbase='/luci-static/aurora'

# Dropbear SSH
uci -q delete dropbear.@dropbear[0]
uci -q add dropbear dropbear
uci -q set dropbear.@dropbear[0].PasswordAuth='on'
uci -q set dropbear.@dropbear[0].RootPasswordAuth='on'
uci -q set dropbear.@dropbear[0].Port='22'
uci -q set dropbear.@dropbear[0].Interface='lan'

uci -q commit network
uci -q commit dhcp
uci -q commit luci
uci -q commit dropbear

/etc/init.d/dropbear enable
/etc/init.d/dropbear restart

rm -rf /tmp/luci-indexcache
rm -rf /tmp/luci-modulecache

exit 0
